[RFC] Tag various character arrays with NGX_NONSTRING.
In nginx we have a number of character arrays which are intentionally
not NUL terminated which GCC 15 will now warn about e.g.

  src/http/v2/ngx_http_v2_filter_module.c:118:36: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (6 chars into 5 available) [-Werror=unterminated-string-initialization]
    118 |     static const u_char nginx[5] = "\x84\xaa\x63\x55\xe7";
        |                                    ^~~~~~~~~~~~~~~~~~~~~~

Fix this by tagging the array with NGX_NONSTRING which will quell this
warning.

Signed-off-by: Andrew Clayton <a.clayton@nginx.com>